// ============================================================
// FinPath — Core Type Definitions
// ============================================================

/** Income source breakdown */
export interface IncomeProfile {
  salary: number;
  freelance: number;
  passive: number;
  /** Total monthly income in INR */
  total: number;
}

/** Expense category breakdown */
export interface ExpenseProfile {
  rent: number;
  food: number;
  transport: number;
  utilities: number;
  entertainment: number;
  other: number;
  /** Total monthly expenses in INR */
  total: number;
}

/** Individual debt item */
export interface DebtItem {
  id: string;
  name: string;
  category: 'homeLoan' | 'carLoan' | 'personalLoan' | 'creditCard' | 'educationLoan' | 'other';
  principal: number;
  interestRate: number; // Annual %
  monthlyPayment: number;
  remainingMonths: number;
}

/** Debt profile summary */
export interface DebtProfile {
  items: DebtItem[];
  /** Total monthly debt payments */
  totalMonthly: number;
}

/** User's financial goal */
export interface Goal {
  id: string;
  name: string;
  icon: string; // Lucide icon name
  category: 'bike' | 'home' | 'travel' | 'debt' | 'education' | 'savings' | 'family' | 'investment' | 'custom';
  targetAmount: number;
  currentAmount: number;
  timelineMonths: number;
  priority: number; // 1 = highest
  status: 'not-started' | 'in-progress' | 'complete';
  /** Monthly allocation determined by plan engine */
  monthlyAllocation: number;
  color: string;
  /** Whether the user has completed the task for this month */
  checkedThisMonth?: boolean;
}

/** Monthly plan entry generated by plan engine */
export interface MonthlyPlan {
  month: number; // 0-indexed from start
  date: string; // "Apr 2026"
  income: number;
  expenses: number;
  debtPayments: number;
  surplus: number;
  /** Per-goal allocations for this month */
  goalAllocations: Record<string, number>;
  /** Milestones hit this month */
  milestones: string[];
  /** Cumulative savings after this month */
  cumulativeSavings: number;
  /** Cumulative net worth estimate */
  netWorth: number;
}

/** Full financial plan output */
export interface FinancialPlan {
  months: MonthlyPlan[];
  totalMonths: number;
  /** Goal completion dates */
  goalCompletionDates: Record<string, string>;
  /** Recommended monthly allocations */
  recommendedAllocations: Record<string, number>;
}

/** Health score breakdown */
export interface HealthScore {
  overall: number; // 0–100
  incomeStability: number;
  debtLoad: number;
  savingsRate: number;
  emergencyFund: number;
  /** Top actions recommended */
  actions: string[];
}

/** Tax calculation result */
export interface TaxResult {
  regime: 'old' | 'new';
  grossIncome: number;
  deductions: number;
  taxableIncome: number;
  tax: number;
  cess: number;
  totalTax: number;
  effectiveRate: number;
  /** Slab-wise breakdown */
  slabs: { range: string; rate: number; tax: number }[];
}

/** Chat message */
export interface ChatMessage {
  id: string;
  role: 'user' | 'penny';
  text: string;
  timestamp: number;
}

/** Scenario for what-if analysis */
export interface Scenario {
  id: string;
  name: string;
  type: 'salary' | 'expense' | 'bonus' | 'market';
  /** Percentage change or absolute amount */
  value: number;
  isPercentage: boolean;
}

/** Complete user financial profile stored in Zustand */
export interface FinancialProfile {
  /** Has the user completed onboarding? */
  onboarded: boolean;
  income: IncomeProfile;
  expenses: ExpenseProfile;
  debts: DebtProfile;
  savings: number;
  investments: number;
  emergencyFund: number;
  goals: Goal[];
  healthScore: HealthScore | null;
  plan: FinancialPlan | null;
  chatHistory: ChatMessage[];
  /** Currency user entered data in */
  currency: string;
  /** When the profile was last updated */
  lastUpdated: number;
}
