// ============================================================
// FinPath — Core Type Definitions
// ============================================================

/** Investment/debt payoff strategy */
export type InvestmentStrategy = 'avalanche' | 'snowball';

/** Where the user's FinancialProfile is persisted */
export type StorageMode = 'local' | 'cloud';

/** How to handle freed allocation when a goal completes */
export type GoalCompletionAction = 'reinvest' | 'surplus';

/** Pending user decision for a completed goal's freed monthly amount */
export interface GoalCompletionDecision {
  goalId: string;
  goalName: string;
  freedMonthlyAmount: number;
  createdAt: number;
}

/** Income source breakdown */
export interface IncomeProfile {
  /** Main job — fixed monthly */
  primary: number;
  /** Second job / gig — fixed monthly */
  secondary: number;
  /** Rental / base dividends — fixed monthly */
  passive: number;
  /** Yield rate — % of passive (dividends, royalties) */
  variablePercent: number;
  /** Computed: passive × variablePercent / 100 */
  variable: number;
  /** Total monthly income in INR */
  total: number;
  /** Annual % growth for primary income */
  primaryIncrement: number;
  /** Annual % growth for secondary income */
  secondaryIncrement: number;
  /** Annual % growth for passive income */
  passiveIncrement: number;
  /** @deprecated use primaryIncrement */
  expectedAnnualIncrement?: number;
  /** Take-home rate applied to primary salary only (0–1). Default 0.88 (88%). Use 1.0 if user entered net directly. */
  netRate: number;
  /** Derived: primary * netRate + secondary + passive + variable. Use this for all affordability/surplus math. */
  netMonthly: number;
}

/** Expense category breakdown */
export interface ExpenseProfile {
  rent: number;
  food: number;
  transport: number;
  utilities: number;
  entertainment: number;
  other: number;
  /** Total monthly expenses in INR */
  total: number;
}

/** Individual debt item */
export interface DebtItem {
  id: string;
  name: string;
  category: 'homeLoan' | 'carLoan' | 'personalLoan' | 'creditCard' | 'educationLoan' | 'other';
  principal: number;
  interestRate: number; // Annual %
  monthlyPayment: number;
  remainingMonths: number;
}

/** Debt profile summary */
export interface DebtProfile {
  items: DebtItem[];
  /** Total monthly debt payments */
  totalMonthly: number;
  /** Total outstanding principal (lumpsum debt) */
  totalPrincipal?: number;
}

/** User's financial goal */
export interface Goal {
  id: string;
  name: string;
  icon: string; // Lucide icon name
  category:
    | 'bike'
    | 'home'
    | 'travel'
    | 'debt'
    | 'education'
    | 'savings'
    | 'family'
    | 'investment'
    | 'custom';
  targetAmount: number;
  currentAmount: number;
  timelineMonths: number;
  priority: number; // 1 = highest
  status: 'not-started' | 'in-progress' | 'complete';
  /** Monthly allocation determined by plan engine */
  monthlyAllocation: number;
  color: string;
  /** Whether the user has completed the task for this month */
  checkedThisMonth?: boolean;
  /** Total lumpsum amounts added to this goal */
  lumpsumAdded?: number;
}

export type CrossGoalInsightTone = 'positive' | 'warning' | 'info';

export interface CrossGoalInsight {
  id: string;
  observation: string;
  action: string;
  impact: string;
  tone: CrossGoalInsightTone;
  icon: string; // Lucide icon name
  priority: number; // 1 = highest
  relatedGoalIds: string[]; // used by Afford screen to filter; [] = global
}

/** Monthly plan entry generated by plan engine */
export interface MonthlyPlan {
  month: number; // 0-indexed from start
  date: string; // "Apr 2026"
  income: number;
  expenses: number;
  debtPayments: number;
  surplus: number;
  /** Portion of monthly surplus intentionally held as net-worth surplus */
  reservedSurplus: number;
  /** Portion temporarily held until user decides reinvest vs surplus */
  pendingSurplus: number;
  /** Per-goal allocations for this month */
  goalAllocations: Record<string, number>;
  /** Milestones hit this month */
  milestones: string[];
  /** Cumulative savings after this month */
  cumulativeSavings: number;
  /** Cumulative net worth estimate */
  netWorth: number;
}

/** Full financial plan output */
export interface FinancialPlan {
  months: MonthlyPlan[];
  totalMonths: number;
  /** Goal completion dates */
  goalCompletionDates: Record<string, string>;
  /** Recommended monthly allocations */
  recommendedAllocations: Record<string, number>;
}

/** Health score breakdown */
export interface HealthScore {
  overall: number; // 0–100
  incomeStability: number;
  debtLoad: number;
  savingsRate: number;
  emergencyFund: number;
  /** Top actions recommended */
  actions: string[];
}

/** Chat message */
export interface ChatMessage {
  id: string;
  role: 'user' | 'penny';
  text: string;
  timestamp: number;
}

/** Completed-goal achievement block in the Sparks ledger (hash-chained). */
export interface Milestone {
  id: string;
  goalId: string;
  title: string;
  category: Goal['category'];
  completedAt: string; // ISO
  amount: number; // goal target amount
  sparks: number; // from computeSparks
  hash: string; // 6-char, deterministic from id
  prevHash: string | null; // chains to previous block; null for first
}

/** A saved affordability scenario ("dream") */
export interface Dream {
  id: string;
  name: string;
  targetCost: number;
  route: 'cash' | 'emi';
  annualInterestRate: number;
  tenureMonths: number;
  /** Cached verdict — refreshed live on /afford screen */
  verdict: 'affordable_now' | 'affordable_later' | 'not_affordable';
  monthsToAfford: number | null;
  savedAt: number;
}

/** Complete user financial profile stored in Zustand */
export interface FinancialProfile {
  /** Has the user completed onboarding? */
  onboarded: boolean;
  /** True when ?demo=1 seeded this profile; bypasses auth gate. */
  demoMode?: boolean;
  income: IncomeProfile;
  expenses: ExpenseProfile;
  debts: DebtProfile;
  savings: number;
  investments: number;
  emergencyFund: number;
  goals: Goal[];
  healthScore: HealthScore | null;
  plan: FinancialPlan | null;
  chatHistory: ChatMessage[];
  /** Currency user entered data in */
  currency: string;
  /** Investment/payoff strategy: avalanche or snowball */
  strategy: InvestmentStrategy;
  /** Monthly amount intentionally diverted to net worth instead of active goals */
  monthlySurplusReserve: number;
  /** Queue of completion decisions awaiting user choice */
  pendingGoalDecisions: GoalCompletionDecision[];
  /** When the profile was last updated */
  lastUpdated: number;
  /** Whether to increment monthly payments with salary growth */
  stepUpEnabled?: boolean;
  /**
   * Expected annual % return on `investments` (compounded monthly inside the
   * plan engine). Driven by the Scenarios risk profile picker:
   * Conservative 7, Balanced 10, Aggressive 14. Defaults to 12 to preserve
   * pre-Phase-3 plan behavior for already-onboarded users.
   */
  investmentReturnRate: number;
  /**
   * Where the profile is persisted. 'local' (default) keeps everything in
   * localStorage. 'cloud' additionally syncs to Supabase via /api/profile
   * so the user can sign in from another browser/device.
   */
  storageMode: StorageMode;
  /**
   * Set to true when the user explicitly deletes the debt goal so that
   * syncDebtGoal does not re-inject it on subsequent store mutations.
   * Reset to false when the debt profile transitions to zero.
   */
  debtGoalDeleted?: boolean;
  /** Hash-chained ledger of completed-goal achievements (Sparks). */
  milestones: Milestone[];
  /** Saved affordability scenarios */
  dreams?: Dream[];
  /** User's age in years — used to cap EMI tenure at retirement */
  ageYears?: number;
}
